Update syncproxy.md
Sarsum/cloudnet-website pull request #5
Opened 2021-04-22 18:05 UTC by QuadrixYT

Add the tip for Custom Tablist(Remove Cloud Tab)

2021-04-22 18:18 UTC, 0utplay commented on versioned_docs/version-3.3/modules/syncproxy.md
> +This is a json array containing the different tablists which are randomly selected.
The tablist is not really random, it's an animation

2021-04-22 18:25 UTC, QuadrixYT commented on versioned_docs/version-3.3/modules/syncproxy.md
> +This is a json array containing the different tablists which are randomly selected.
Is fixed in new Commit

2021-04-22 18:32 UTC, 0utplay commented on versioned_docs/version-3.3/modules/syncproxy.md
> +This is a json array containing the different tablists which are playing in a animation.
an animation

2021-04-22 18:49 UTC, derklaro requested changes

2021-04-22 18:49 UTC, derklaro commented on versioned_docs/version-3.3/modules/syncproxy.md
> +This is a json array containing the different tablists which are playing in an animation.
In my opinion

```suggestion
It is a json array of the different animations that are displayed in the tablist one after the other.
```

would fit better

2021-04-22 18:51 UTC, QuadrixYT commented on versioned_docs/version-3.3/modules/syncproxy.md
> +This is a json array containing the different tablists which are playing in an animation.
Ok i will change it to that

2021-04-24 13:56 UTC, Sarsum approved these changes
Looks fine, thank you!

2021-04-24 13:57 UTC, merged