Rephrase some explanations and add some missing things
Sarsum/cloudnet-website pull request #61
Opened 2021-08-03 18:32 UTC by 0utplay

2021-08-03 20:54 UTC, GiantTreeLP commented on versioned_docs/version-3.4/commands/report.md
> +This can be requested in the [support](../index.md#support), so that better help can be provided.
What does "this" refer to?

2021-08-03 20:54 UTC, GiantTreeLP commented on versioned_docs/version-3.4/commands/service.md
> +The command is useful if new inclusions are added or updated, and they need to be updated in the service
```suggestion
It's useful if new inclusions are added or updated, and they need to be updated for the service
```
This phrasing is better in my opinion

2021-08-03 20:54 UTC, GiantTreeLP commented on versioned_docs/version-3.4/commands/service.md
> +The command is useful if new templates are added or updated, and they need to be updated in the service
```suggestion
It's useful if new templates are added or updated, and they need to be updated for the service
```
This phrasing is better in my opinion

2021-08-03 20:54 UTC, GiantTreeLP commented on versioned_docs/version-3.4/commands/template.md
> +This command copies the given `sourceTemplate` to the given `targetTemplate`.
Are backticks properly supported?

2021-08-03 20:54 UTC, GiantTreeLP commented on versioned_docs/version-3.4/components/tasks.md
> +If this option is turned off, the port and IP in the server software configuration will not be changed by CloudNet
```suggestion
If this option is turned off, the port and IP in the server software configuration will not be changed by CloudNet.
```

Make sure to use proper punctuation.

2021-08-04 08:58 UTC, 0utplay commented on versioned_docs/version-3.4/commands/template.md
> +This command copies the given `sourceTemplate` to the given `targetTemplate`.
They are used frequently so I assume that they are

2021-08-04 14:29 UTC, derklaro requested changes

2021-08-04 14:29 UTC, derklaro commented on versioned_docs/version-3.4/commands/players.md
> +The `--force` argument can be used to force kick a player so that the player is removed from all caches
```suggestion
If the `--force` argument is provided the player will not only get kicked from the entire network but also removed from all caches. This might be helpful if a player get's disconnected because of `You are already connected to this network`.
```

2021-08-04 14:29 UTC, derklaro commented on versioned_docs/version-3.4/commands/report.md
> +This information can be requested in the [support](../index.md#support), so that better help can be provided.
I don't get this big change of the phrase... I guess this might be enough:

```suggestion
These information might be requested by our [support team](../index.md#support) to assist you with your support enquiry.
```

2021-08-04 14:29 UTC, derklaro commented on versioned_docs/version-3.4/commands/service.md
> +description: Manages all services on the local node and in the cluster
In my opinion
```suggestion
description: Manages all services in the cluster
```
is enough to understand what the command does, but it might be confusing for unexperienced users.

2021-08-04 14:29 UTC, derklaro commented on versioned_docs/version-3.4/commands/service.md
> +It's useful if new inclusions are added or updated, and they need to be updated for the service
The `and they need to be updated for the service` part is definitely confusing. Also the inclusions were added.

2021-08-04 14:29 UTC, derklaro commented on versioned_docs/version-3.4/commands/service.md
> +It's useful if new templates are added or updated, and they need to be updated for the service
Same thing here.

2021-08-04 14:29 UTC, derklaro commented on versioned_docs/version-3.4/components/groups.md
> +Groups are intended to summarize [services](services.md) and [tasks](tasks.md). Each service belongs to one task, and tasks can be grouped using groups
Groups are not intended to summarise (typo btw) services, only tasks - tasks are intended to summarise services. So i guess the hole sentence should be re-written.

2021-08-04 14:29 UTC, derklaro commented on versioned_docs/version-3.4/components/tasks.md
> +If this option is turned off, the port and IP in the server software configuration will not be changed by CloudNet.
I'm unsure: is `will not get changed` better here?

2021-08-04 20:16 UTC, 0utplay commented on versioned_docs/version-3.4/components/tasks.md
> +If this option is turned off, the port and IP in the server software configuration will not be changed by CloudNet.
I think both versions are okay

2021-08-05 14:53 UTC, 0utplay commented on versioned_docs/version-3.4/commands/report.md
> +This information can be requested in the [support](../index.md#support), so that better help can be provided.
I don't see the problem rephrasing it completely

2021-08-05 14:58 UTC, 0utplay commented on versioned_docs/version-3.4/components/groups.md
> +Groups are intended to summarize [services](services.md) and [tasks](tasks.md). Each service belongs to one task, and tasks can be grouped using groups
I don't see any typos there?

2021-08-05 16:26 UTC, GiantTreeLP commented on versioned_docs/version-3.4/components/groups.md
> +Groups are intended to summarize [services](services.md) and [tasks](tasks.md). Each service belongs to one task, and tasks can be grouped using groups
@derklaro btw, summarised and summarized are both correct, the "s" is typical for British English, the "z" for American English. (You also made the same "mistake")

2021-08-05 16:46 UTC, derklaro commented on versioned_docs/version-3.4/components/groups.md
> +Groups are intended to summarize [services](services.md) and [tasks](tasks.md). Each service belongs to one task, and tasks can be grouped using groups
I was thinking that we are using UK english, but @0utplay told me that there is no definition which form to use...

2021-08-06 21:28 UTC, GiantTreeLP commented on versioned_docs/version-3.4/components/groups.md
> +Groups are intended to summarize [services](services.md) and [tasks](tasks.md). Each service belongs to one task, and tasks can be grouped using groups
Well, it should be consistent

2021-08-14 12:06 UTC, derklaro approved these changes

2021-08-23 17:56 UTC, Sarsum requested changes

2021-08-23 17:56 UTC, Sarsum commented on versioned_docs/version-3.4/commands/service.md
> +It's useful if new inclusions are added or updated, and they need to be updated for the service
We shouldn't use the short forms in "official texts"

2021-08-23 17:56 UTC, Sarsum commented on versioned_docs/version-3.4/commands/service.md
> +It's useful if new templates are added or updated, and they need to be updated for the service
Same as above

2021-08-23 17:56 UTC, Sarsum commented on versioned_docs/version-3.4/commands/template.md
> +This command copies the given `sourceTemplate` to the given `targetTemplate`.
I think we should state the explanation separated from the variable name like "the given source template `sourceTemplate`) because it makes the different translations more consistent.

2021-08-23 17:56 UTC, Sarsum commented on versioned_docs/version-3.4/components/groups.md
> +Groups are intended to summarize [tasks](tasks.md). Each service belongs to one task, and tasks can be grouped using groups
You might use "assorted using groups" instead, which makes the language more varied.

2021-08-24 18:14 UTC, 0utplay commented on versioned_docs/version-3.4/components/groups.md
> +Groups are intended to summarize [tasks](tasks.md). Each service belongs to one task, and tasks can be grouped using groups
I don't think that a task is sorted by a group

2021-08-30 13:06 UTC, Sarsum commented on versioned_docs/version-3.4/components/groups.md
> +Groups are intended to summarize [tasks](tasks.md). Each service belongs to one task, and tasks can be grouped using groups
How about "can be combined using groups"?

2021-09-17 17:56 UTC, Sarsum approved these changes
LGTM

2021-09-17 17:57 UTC, merged